version: "3.3"
services:
  mysql:
    image: mysql:8.0
    container_name: db-for-go
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=caching_sha2_password
    environment:
      # MYSQL_ROOT_USER: ${ROOTUSER}
      # MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      # MYSQL_DATABASE: ${DATABASE}
      # MYSQL_USER: ${USERNAME}
      # MYSQL_PASSWORD: ${USERPASS}
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: sampledb
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
