version: "3.8"

services:
  jupyterlab:
    platform: linux/amd64
    build: .
    container_name: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --IdentityProvider.token=''
